name: 'Saved replies'
description: 'Trigger replies on GitHub Issues and Pull Requests'
author: 'Gerome Grignon'
inputs:
  token:
    description: 'GitHub Personal Access Token'
    required: true
  addedLabels:
    description: 'comma seperated stringified list of labels to add'
    required: false
  removedLabels:
    description: 'comma seperated stringified of labels to remove'
    required: false
  reply:
    description: 'reply'
    required: false
  assigneesAdded:
    description: 'comma seperated stringified list of assignees to add'
    required: false
  assigneesRemoved:
    description: 'comma seperated stringified list of assignees to remove'
    required: false
  reviewersAdded:
    description: 'comma seperated stringified list of reviewers to add'
    required: false
  reviewersRemoved:
    description: 'comma seperated stringified list of reviewers to remove'
    required: false
  action:
    description: 'action to perform (add or update). default to add'
    required: true
    default: 'add'
  state:
    description: 'new issue state (open or closed)'
    required: false
  clearLabels:
    description: 'comma seperated stringified list of assignees to remove'
    required: false
  clearAssignees:
    description: 'comma seperated stringified list of assignees to remove'
    required: false
  clearReviewers:
    description: 'comma seperated stringified list of assignees to remove'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
